on:
  push:
    branches:
    - master

jobs:
  test:
    name: run unit test
    runs-on: ubuntu-22.04
    steps:
      - name: run unit test
        run: |
          echo "misal ini akan menjalankan unit test"
      - name: list file
        run: |
          ls -la
      - name: download/clone respository
        uses: actions/checkout@v4
      - name: list file
        run: |
          ls -la

  build:
    name: build applicatiom
    runs-on: ubuntu-22.04
    needs:
    - test
    steps:
      - name: run build
        run: |
          echo "misal ini akan build/package aplikasi"

  deploy:
    name: deploy applicatiom
    runs-on: ubuntu-22.04
    needs:
    - build
    steps:
      - name: run build
        run: |
          echo "misal ini akan deploy aplikasi ke server"