on:
  push:
    branches:
    - master

jobs:
  test:
    name: run unit test
    runs-on: ubuntu-22.04
    steps:
      - name: run unit test
        run: |
          echo "misal ini akan menjalankan unit test"

  buid:
    name: build applicatiom
    runs-on: ubuntu-22.04
    steps:
      - name: run build
        run: |
          echo "misal ini akan build/package aplikasi"

  build:
    name: deploy applicatiom
    runs-on: ubuntu-22.04
    steps:
      - name: run build
        run: |
          echo "misal ini akan deploy aplikasi ke server"